default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>

development: *default

test: *default

production: *default
